<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>AutoHost</AssemblyName>
    <RootNamespace>AutoHost</RootNamespace>
  </PropertyGroup>

  <!-- BepInEx -->
  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>lib/BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>lib/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <!-- Unity -->
  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>lib/UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>lib/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>lib/UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <!-- Mirror -->
  <ItemGroup>
    <Reference Include="Mirror">
      <HintPath>lib/Mirror.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <!-- Steamworks -->
  <ItemGroup>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>lib/com.rlabrecque.steamworks.net.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <!-- PlayMaker -->
  <ItemGroup>
    <Reference Include="PlayMaker">
      <HintPath>lib/PlayMaker.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <!-- Game -->
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>lib/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>lib/Assembly-CSharp-firstpass.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
